### ISSUE TITLE
Dinos always look right when standing still

### ISSUE THREAD

**Issue by patrakov** [Frunit/qpop.js#6]
To reproduce:

1. Find yourself in a situation when there is a female and a dino, and the dino is on the right, going left and looking left.
2. Mate.

Actual result: the dino is facing right.
Expected result: the dino should be facing the direction where it was moving before. I.e., in this example, left.

Instead of mating, some (but not all) other methods of making sure that the dino stands still also work, e.g. when one dino in a narrow passage has to wait for the other.

**Comment by Frunit** [comment]
Yes, this is a thing I also thought about. I would have liked the player character to stand in the direction of last movement, so if the player just moved to the right, the figure should stand to the right as well.
The problem is that there are no graphics for a dino looking left while standing in the original game. I attached a random screenshot where I manually pasted the dino facing right (original) and left (mirrored). The game graphics are displayed as if the light is coming from the left. You can see that on the dino, but also on the tree and volcano below. The mirrored dino looks like the light comes from the right which looks just wrong. The same problem occurs when using mirrored versions of any other species to make them look in the other direction while standing. So I decided to stick to the original behaviour and let the dino always look to the right, even if the player is to the left.

![example](https://user-images.githubusercontent.com/46853107/108596128-5510b380-7383-11eb-95da-769acf21b91a.png)

**Comment by patrakov** [comment]
OK. The question (I guess, to the original authors) is, why do we need the image of a standing-still dino at all? Maybe just freeze it?

**Comment by Frunit** [comment]
Well, it is used whenever there is some player action where NPCs don't move, like fight or mating. Also, if the predator is trapped somewhere, it cannot move, so it stands still. The moving sprites would look strange when standing still.
